"""add savol_rasm_style

Revision ID: 54545bfdc2ce
Revises: 84e45aeb93c9
Create Date: 2026-08-04 17:21:40.658026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54545bfdc2ce'
down_revision: Union[str, Sequence[str], None] = '84e45aeb93c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('savol_rasm_style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'savol_rasm_style')
    # ### end Alembic commands ###
