"""add exam name

Revision ID: 84e45aeb93c9
Revises: a1c950a70b79
Create Date: 2026-08-01 16:01:36.704626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e45aeb93c9'
down_revision: Union[str, Sequence[str], None] = 'a1c950a70b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'name')
    # ### end Alembic commands ###
