"""add question bank tables

Revision ID: 94472c55d2d9
Revises: 7d759cc754f8
Create Date: 2026-08-30 17:16:12.377819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '94472c55d2d9'
down_revision: Union[str, Sequence[str], None] = '7d759cc754f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_bank_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.String(), nullable=False),
    sa.Column('fan', sa.String(), nullable=False),
    sa.Column('kitob_nomi', sa.String(), nullable=True),
    sa.Column('bolim_nomi', sa.String(), nullable=True),
    sa.Column('savol_html', sa.Text(), nullable=False),
    sa.Column('savol_rasm_url', sa.String(), nullable=True),
    sa.Column('savol_rasm_style', sa.String(), nullable=True),
    sa.Column('jadval_html', sa.Text(), nullable=True),
    sa.Column('variant_a_html', sa.Text(), nullable=False),
    sa.Column('variant_b_html', sa.Text(), nullable=False),
    sa.Column('variant_c_html', sa.Text(), nullable=False),
    sa.Column('variant_d_html', sa.Text(), nullable=False),
    sa.Column('togri_javob', sa.String(length=1), nullable=False),
    sa.Column('ball', sa.Float(), nullable=False),
    sa.Column('times_shown', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('difficulty_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_items_bolim_nomi'), 'question_bank_items', ['bolim_nomi'], unique=False)
    op.create_index(op.f('ix_question_bank_items_fan'), 'question_bank_items', ['fan'], unique=False)
    op.create_index(op.f('ix_question_bank_items_kitob_nomi'), 'question_bank_items', ['kitob_nomi'], unique=False)
    op.create_index(op.f('ix_question_bank_items_teacher_id'), 'question_bank_items', ['teacher_id'], unique=False)
    op.create_table('toplamlar',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('savollar_soni', sa.Integer(), nullable=False),
    sa.Column('qiyinchilik_maqsadi_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toplamlar_teacher_id'), 'toplamlar', ['teacher_id'], unique=False)
    op.create_table('toplam_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('toplam_id', sa.String(), nullable=False),
    sa.Column('bank_item_id', sa.String(), nullable=False),
    sa.Column('tartib', sa.Integer(), nullable=False),
    sa.Column('ball', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bank_item_id'], ['question_bank_items.id'], ),
    sa.ForeignKeyConstraint(['toplam_id'], ['toplamlar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toplam_questions_bank_item_id'), 'toplam_questions', ['bank_item_id'], unique=False)
    op.create_index(op.f('ix_toplam_questions_toplam_id'), 'toplam_questions', ['toplam_id'], unique=False)
    op.drop_column('processing_jobs', 'payload_json')
    op.drop_column('processing_jobs', 'result_json')
    op.drop_column('processing_jobs', 'attempts')
    op.add_column('question_attempts', sa.Column('bank_item_id', sa.String(), nullable=True))
    op.alter_column('question_attempts', 'question_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_question_attempts_bank_item_id'), 'question_attempts', ['bank_item_id'], unique=False)
    op.create_foreign_key(None, 'question_attempts', 'question_bank_items', ['bank_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_question_attempts_bank_item_id'), table_name='question_attempts')
    op.alter_column('question_attempts', 'question_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('question_attempts', 'bank_item_id')
    op.add_column('processing_jobs', sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
    op.add_column('processing_jobs', sa.Column('result_json', sqlite.JSON(), nullable=True))
    op.add_column('processing_jobs', sa.Column('payload_json', sqlite.JSON(), nullable=True))
    op.drop_index(op.f('ix_toplam_questions_toplam_id'), table_name='toplam_questions')
    op.drop_index(op.f('ix_toplam_questions_bank_item_id'), table_name='toplam_questions')
    op.drop_table('toplam_questions')
    op.drop_index(op.f('ix_toplamlar_teacher_id'), table_name='toplamlar')
    op.drop_table('toplamlar')
    op.drop_index(op.f('ix_question_bank_items_teacher_id'), table_name='question_bank_items')
    op.drop_index(op.f('ix_question_bank_items_kitob_nomi'), table_name='question_bank_items')
    op.drop_index(op.f('ix_question_bank_items_fan'), table_name='question_bank_items')
    op.drop_index(op.f('ix_question_bank_items_bolim_nomi'), table_name='question_bank_items')
    op.drop_table('question_bank_items')
    # ### end Alembic commands ###
